FROM node:alpine

WORKDIR /usr/app

COPY package.json .
RUN npm config set unsafe-perm true
RUN npm install --silent
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .

CMD [ "npm", "run", "start" ]